config/routes.rb
Rails.application.routes.draw do
  get 'home/painting'
  post 'home/make_public'
  resources :home
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  devise_scope :user do
    authenticated :user do
   
       get '/users/sign_out' => 'devise/sessions#destroy'
       root 'home#dashboard', as: :authenticated_root
    end
    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def painting
  		@painting = Painting.where(user_id: params[:user_id]).where(public: true)
  	if !@painting.present?
  		flash[:alert] = "No public painting available for the Artist"
  	end
  end

  def dashboard
  	@paintings_all = current_user.paintings
  	@painting = Painting.new
  end

	def create
	  @painting = Painting.new(user_params)
	  @painting.user_id = current_user.id
	  if @painting.save
	  	flash[:notice] = "Painting saved succesfully"
			redirect_to authenticated_root_path	
		else
			flash[:notice] = "Unable to Save something went wrong"
			redirect_to authenticated_root_path
		end
	end

	def make_public
		if params[:id] and params[:checked] == "true"
			@painting = Painting.find(params[:id])
			@painting.update_attributes(public: true)
			flash[:notice] = "Painting is public now"
			render :text => "Success"
		elsif params[:id] and params[:checked] == "false"
			@painting = Painting.find(params[:id])
			@painting.update_attributes(public: false)
			flash[:notice] = "Painting is no more public"
			render :text => "Success"
		else
			flash[:notice] = "Unable to make public something went wrong"
			render :text => "Error"
		end
	end

	private
	def user_params
	  params.require(:painting).permit(:picture)
	end

end

app/views/home/dashboard.html.erb
<div class="card">
    <div class="card-body text-center">
        <div class="row">
            <div class="col-lg-3">
                <div class="card">
                <div class="card-body text-center">
                <div class="card-img-actions d-inline-block mb-3">
                    <% if current_user.avatar.present?  %>
                    <%= image_tag(current_user.avatar.url(:medium), :size => "166x170") %>
                    <% else %>
                    <!-- <img class="card-img img-fluid" src="/assets/placeholder.jpg" alt="" height="170" width="166"> -->
                    <%= image_tag("/assets/placeholder.jpg", :size => "166x170", :class => "img-fluid rounded-circle") %>
                    <% end %>
                </div>
                <h6 class="font-weight-semibold mb-0">
                    <%= current_user.name%>
                </h6>
                <div class="list-icons list-icons-extended mt-3">
                    <a href="#" data-dismiss="modal" data-toggle="modal" data-target="#avatar_upload" class="btn btn-primary btn-file ml-auto">Upload Profile Picture</a>
                </div>
                </div>
                </div>
            </div>
            <div class="col-lg-9">
                <!-- <div class="card"> -->
                <div class="card-header header-elements-inline">
                    <h6 class="card-title"><b>
                            <%= current_user.name %></b> <br>
                        <%= current_user.city %>,
                        <%= current_user.country %>
                    </h6>
                    <div class="header-elements">
                        <div class="list-icons">
                            <a href="#" data-dismiss="modal" data-toggle="modal" data-target="#modal_edit" class="ml-auto">Edit Profile</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>
                                    <%= current_user.about%></label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-9">
                            <div class="form-group">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label>
                                    <%= current_user.email %> |
                                    <%= current_user.phone %></label>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- </div> -->
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <h6 class="card-title"> <a href="#" class="breadcrumb-item">PAINTINGS</a></h6>
            </div>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
        <div class="header-elements d-none">
            <div class="breadcrumb justify-content-center">
                <a href="#" data-dismiss="modal" data-toggle="modal" data-target="#painting_upload" class="btn btn-primary btn-file ml-auto">Add Painting</a>
            </div>
        </div>
    </div>
    <div class="row">
        <% @paintings_all.each do |paint|%>
        <div class="col-xl-3 col-sm-6">
            <div class="card">
                <div class="card-img-actions px-1 pt-1">
                    <%= image_tag(paint.picture.url(:medium), :size => "420x200") %>
                </div>
                <div class="card-body text-center">
                    <h6 class="font-weight-semibold">Painting</h6>
<!--                       <label>
                          <div class="uniform-checker"><span class=""><input type="checkbox" class="form-check-input-styled"></span></div>Mark Public
                      </label> -->
                    <%= check_box_tag 'Public', paint.id, paint.public, :data => {:remote => true, :url => url_for( :action => 'make_public'), :id => paint.id, :method => :put}, :class => 'input-large' %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>
<div id="modal_edit" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit Profile</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div class="card">
                    <div class="card-body">
                        <% resource = current_user %>
                        <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
                        <%= devise_error_messages! %>
                        <div class="form-group request">
                            <label>Name:</label>
                            <input type="text" class="form-control" name="user[name]" placeholder="Name" required value="<%=  resource.name || '' %>">
                        </div>
                        <div class="form-group">
                            <label>Email:</label>
                            <input type="text" class="form-control" name="user[email]" placeholder="Email" required value="<%= resource.email || '' %>">
                        </div>
                        <div class="form-group">
                            <label>Phone:</label>
                            <input type="text" class="form-control" name="user[phone]" placeholder="Phone" required value="<%= resource.phone || '' %>">
                        </div>
                        <div class="form-group">
                            <label>City:</label>
                            <input type="text" class="form-control" name="user[city]" placeholder="City" required value="<%= resource.city || '' %>">
                        </div>
                        <div class="form-group">
                            <label>Country:</label>
                            <input type="text" class="form-control" name="user[country]" placeholder="Country" required value="<%= resource.country || '' %>">
                        </div>
                        <div class="form-group">
                            <label>Username:</label>
                            <input type="text" class="form-control" name="user[username]" placeholder="Username" required value="<%= resource.username || '' %>">
                        </div>
                        <div class="form-group">
                            <label>New Password:</label>
                            <input type="password" class="form-control" name="user[password]" placeholder="password" value="<%= resource.password || '' %>">
                        </div>
                        <div class="form-group row">
                            <label>About:</label>
                            <textarea rows="5" cols="5" class="form-control" name="user[about]" required placeholder="Enter your message here"><%= resource.about || '' %></textarea>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Save</i></button>
                        </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="avatar_upload" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Upload Profile Image</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div class="card">
                    <div class="card-body">
                        <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put, multipart: true }) do |f| %>
                        <%= devise_error_messages! %>
                        <div class="form-group request">
                            <div class="uniform-uploader"><input type="file" name="user[avatar]" required class="form-input-styled" data-fouc=""><span class="filename" style="user-select: none;">No file selected</span><span class="action btn bg-pink-400" style="user-select: none;">Choose File</span></div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Upload</button>
                        </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="painting_upload" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Upload Painting</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div class="card">
                    <div class="card-body">
                        <%= form_for @painting, url: home_index_path, html: {method: :post, multipart: true } do |form| %>
                        <div class="form-group request">
                            <div class="uniform-uploader"><input type="file" name="painting[picture]" required class="form-input-styled" data-fouc=""><span class="filename" style="user-select: none;">No file selected</span><span class="action btn bg-pink-400" style="user-select: none;">Choose File</span></div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Upload</button>
                        </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
  $('.input-large').click(function() {
  var checked; 
  if ($(this).is(':checked')) {
    checked = true;
  } else {
    checked = false;
  } 
  $.ajax({
      type: "POST",
      url: "/home/make_public",
      data: { id: $(this).data("id"), checked: checked }
   });     
});
</script>

app/views/home/painting.html.erb
<div class="content">
   <div class="row">
     <h1><--<%= link_to 'Back', :back  %></h1>
   </div>
    <div class="row">
      <% @count = 0%>
      <% @painting.each do |paint|%>
     
        <div class="col-xl-3 col-sm-6">
            <div class="card">
                <div class="card-img-actions px-1 pt-1">
                     <%= image_tag(paint.picture.url(:medium), :size => "420x200") %>
                </div>
                <div class="card-body text-center">
                     <h6 class="font-weight-semibold">Painting-<%= @count += 1 %></h6>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>